flags = {
    "AAA": {
        "undefined": ["OF", "SF", "ZF", "PF"],
        "defined": ["AF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["AF"],
        "cleared": [],
    },
    "AAD": {
        "undefined": ["OF", "AF", "CF"],
        "defined": ["SF", "ZF", "PF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "AAM": {
        "undefined": ["OF", "AF", "CF"],
        "defined": ["SF", "ZF", "PF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "AAS": {
        "undefined": ["OF", "SF", "ZF", "PF"],
        "defined": ["AF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["AF"],
        "cleared": [],
    },
    "ADC": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["CF"],
        "cleared": [],
    },
    "ADD": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "ADX": {
        "undefined": ["OF", "AF", "CF"],
        "defined": ["SF", "ZF", "PF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "AMX": {
        "undefined": ["OF", "AF", "CF"],
        "defined": ["SF", "ZF", "PF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "AND": {
        "undefined": ["AF"],
        "defined": ["OF", "SF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": ["OF", "CF"],
    },
    "ARPL": {
        "undefined": [],
        "defined": ["ZF"],
        "setted": [],
        "modified": ["ZF"],
        "tested": [],
        "cleared": [],
    },
    "BOUND": {
        "undefined": [],
        "defined": ["IF"],
        "setted": [],
        "modified": ["IF"],
        "tested": [],
        "cleared": ["IF"],
    },
    "BSF": {
        "undefined": ["OF", "SF", "AF", "PF", "CF"],
        "defined": ["ZF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "BSR": {
        "undefined": ["OF", "SF", "AF", "PF", "CF"],
        "defined": ["ZF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "BT": {
        "undefined": ["OF", "SF", "ZF", "AF", "PF"],
        "defined": ["CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "BTC": {
        "undefined": ["OF", "SF", "ZF", "AF", "PF"],
        "defined": ["CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "BTR": {
        "undefined": ["OF", "SF", "ZF", "AF", "PF"],
        "defined": ["CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "BTS": {
        "undefined": ["OF", "SF", "ZF", "AF", "PF"],
        "defined": ["CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "CLC": {
        "undefined": [],
        "defined": ["CF"],
        "setted": [],
        "modified": ["CF"],
        "tested": [],
        "cleared": ["CF"],
    },
    "CLD": {
        "undefined": [],
        "defined": ["DF"],
        "setted": [],
        "modified": ["DF"],
        "tested": [],
        "cleared": ["DF"],
    },
    "CLI": {
        "undefined": [],
        "defined": ["IF"],
        "setted": [],
        "modified": ["IF"],
        "tested": [],
        "cleared": ["IF"],
    },
    "CMC": {
        "undefined": [],
        "defined": ["CF"],
        "setted": [],
        "modified": ["CF"],
        "tested": ["CF"],
        "cleared": [],
    },
    "CMOVA": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "CMOVAE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "CMOVB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "CMOVBE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "CMOVC": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "CMOVE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "CMOVG": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "CMOVGE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "CMOVL": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "CMOVLE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "CMOVNA": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "CMOVNAE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "CMOVNB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "CMOVNBE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "CMOVNC": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "CMOVNE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "CMOVNG": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "CMOVNGE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "CMOVNL": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "CMOVNLE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "CMOVNO": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF"],
        "cleared": [],
    },
    "CMOVNP": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "CMOVNS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["SF"],
        "cleared": [],
    },
    "CMOVNZ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "CMOVO": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF"],
        "cleared": [],
    },
    "CMOVP": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "CMOVPE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "CMOVPO": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "CMOVS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["SF"],
        "cleared": [],
    },
    "CMOVZ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "CMP": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "CMPS": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["DF"],
        "cleared": [],
    },
    "CMPSB": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["DF"],
        "cleared": [],
    },
    "CMPSD": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["DF"],
        "cleared": [],
    },
    "CMPSQ": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["DF"],
        "cleared": [],
    },
    "CMPSW": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["DF"],
        "cleared": [],
    },
    "CMPXCHG": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
        "regs": ["RAX"],
    },
    "CMPXCHG16B": {
        "undefined": [],
        "defined": ["ZF"],
        "setted": [],
        "modified": ["ZF"],
        "tested": [],
        "cleared": [],
    },
    "CMPXCHG8B": {
        "undefined": [],
        "defined": ["ZF"],
        "setted": [],
        "modified": ["ZF"],
        "tested": [],
        "cleared": [],
        "regs": ["RAX", "RDX", "RCX", "RBX"],
    },
    "COMISD": {
        "undefined": [],
        "defined": ["ZF", "PF", "CF"],
        "setted": [],
        "modified": ["ZF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "COMISS": {
        "undefined": [],
        "defined": ["ZF", "PF", "CF"],
        "setted": [],
        "modified": ["ZF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "DAA": {
        "undefined": ["OF"],
        "defined": ["SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["AF", "CF"],
        "cleared": [],
    },
    "DAS": {
        "undefined": ["OF"],
        "defined": ["SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["AF", "CF"],
        "cleared": [],
    },
    "DEC": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF"],
        "tested": [],
        "cleared": [],
    },
    "DIV": {
        "undefined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "defined": [],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
        "regs": ["RDX", "RAX"],
    },
    "FCMOVB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "FCMOVBE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "FCMOVE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "FCMOVNB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "FCMOVNBE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "FCMOVNE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "FCMOVNU": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "FCMOVU": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "FCOMI": {
        "undefined": [],
        "defined": ["OF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "ZF", "PF", "CF"],
        "tested": [],
        "cleared": ["OF"],
    },
    "FCOMIP": {
        "undefined": [],
        "defined": ["OF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "ZF", "PF", "CF"],
        "tested": [],
        "cleared": ["OF"],
    },
    "FUCOMI": {
        "undefined": [],
        "defined": ["OF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "ZF", "PF", "CF"],
        "tested": [],
        "cleared": ["OF"],
    },
    "FUCOMIP": {
        "undefined": [],
        "defined": ["OF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "ZF", "PF", "CF"],
        "tested": [],
        "cleared": ["OF"],
    },
    "ICEBP": {
        "undefined": [],
        "defined": ["IF"],
        "setted": [],
        "modified": ["IF"],
        "tested": [],
        "cleared": ["IF"],
    },
    "IDIV": {
        "undefined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "defined": [],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
        "regs": ["RDX", "RAX"],
    },
    "IMUL": {
        "undefined": ["SF", "ZF", "AF", "PF"],
        "defined": ["OF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "INC": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF"],
        "tested": [],
        "cleared": [],
    },
    "INS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "INSB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "INSD": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "INSW": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "INT": {
        "undefined": [],
        "defined": ["IF"],
        "setted": [],
        "modified": ["IF"],
        "tested": [],
        "cleared": ["IF"],
    },
    "INT1": {
        "undefined": [],
        "defined": ["IF"],
        "setted": [],
        "modified": ["IF"],
        "tested": [],
        "cleared": ["IF"],
    },
    "INTO": {
        "undefined": [],
        "defined": ["IF"],
        "setted": [],
        "modified": ["IF"],
        "tested": ["OF"],
        "cleared": ["IF"],
    },
    "INVEPT": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "INVVPID": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "JA": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "JAE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "JB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "JBE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "JC": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "JE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "JG": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "JGE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "JL": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "JLE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "JNA": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "JNAE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "JNB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "JNBE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "JNC": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "JNE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "JNG": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "JNGE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "JNL": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "JNLE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "JNO": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF"],
        "cleared": [],
    },
    "JNP": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "JNS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["SF"],
        "cleared": [],
    },
    "JNZ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "JO": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF"],
        "cleared": [],
    },
    "JP": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "JPE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "JPO": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "JS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["SF"],
        "cleared": [],
    },
    "JZ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "LAHF": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["SF", "ZF", "AF", "PF", "CF"],
        "cleared": [],
    },
    "LAR": {
        "undefined": [],
        "defined": ["ZF"],
        "setted": [],
        "modified": ["ZF"],
        "tested": [],
        "cleared": [],
    },
    "LODS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "LODSB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "LODSD": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "LODSQ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "LODSW": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "LOOPE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "LOOPNE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "LOOPNZ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "LOOPZ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "LSL": {
        "undefined": [],
        "defined": ["ZF"],
        "setted": [],
        "modified": ["ZF"],
        "tested": [],
        "cleared": [],
    },
    "MOV": {
        "undefined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "defined": [],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "MOVS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "MOVSB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "MOVSD": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "MOVSQ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "MOVSW": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "MUL": {
        "undefined": ["SF", "ZF", "AF", "PF"],
        "defined": ["OF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
        "regs": ["RDX", "RAX"],
    },
    "NEG": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "OR": {
        "undefined": ["AF"],
        "defined": ["OF", "SF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": ["OF", "CF"],
    },
    "OUTS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "OUTSB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "OUTSD": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "OUTSW": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "PCMPESTRI": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": ["AF", "PF"],
    },
    "PCMPESTRM": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": ["AF", "PF"],
    },
    "PCMPISTRI": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": ["AF", "PF"],
    },
    "PCMPISTRM": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": ["AF", "PF"],
    },
    "POPCNT": {
        "undefined": [],
        "defined": ["AF", "OF", "ZF", "CF", "PF", "SF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": ["OF", "SF", "AF", "PF", "CF"],
    },
    "PTEST": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": ["OF", "SF", "AF", "PF"],
    },
    "RCL": {
        "undefined": ["SF", "ZF", "AF", "PF"],
        "defined": ["OF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["CF"],
        "cleared": [],
    },
    "RCR": {
        "undefined": ["SF", "ZF", "AF", "PF"],
        "defined": ["OF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["CF"],
        "cleared": [],
    },
    "REPE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "REPNE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "REPNZ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "REPZ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "ROL": {
        "undefined": ["SF", "ZF", "AF", "PF"],
        "defined": ["OF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "ROR": {
        "undefined": ["SF", "ZF", "AF", "PF"],
        "defined": ["OF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "SAHF": {
        "undefined": [],
        "defined": ["SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "SAL": {
        "undefined": ["AF"],
        "defined": ["OF", "SF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "SALC": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "SAR": {
        "undefined": ["AF"],
        "defined": ["OF", "SF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "SBB": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["CF"],
        "cleared": [],
    },
    "SCAS": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["DF"],
        "cleared": [],
    },
    "SCASB": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["DF"],
        "cleared": [],
    },
    "SCASD": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["DF"],
        "cleared": [],
    },
    "SCASQ": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["DF"],
        "cleared": [],
    },
    "SCASW": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": ["DF"],
        "cleared": [],
    },
    "SETA": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "SETAE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "SETALC": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "SETB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "SETBE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "SETC": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "SETE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "SETG": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "SETGE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "SETL": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "SETLE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "SETNA": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "SETNAE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "SETNB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "SETNBE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF", "CF"],
        "cleared": [],
    },
    "SETNC": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["CF"],
        "cleared": [],
    },
    "SETNE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "SETNG": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "SETNGE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "SETNL": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF"],
        "cleared": [],
    },
    "SETNLE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF", "SF", "ZF"],
        "cleared": [],
    },
    "SETNO": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF"],
        "cleared": [],
    },
    "SETNP": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "SETNS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["SF"],
        "cleared": [],
    },
    "SETNZ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "SETO": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["OF"],
        "cleared": [],
    },
    "SETP": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "SETPE": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "SETPO": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["PF"],
        "cleared": [],
    },
    "SETS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["SF"],
        "cleared": [],
    },
    "SETZ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["ZF"],
        "cleared": [],
    },
    "SHL": {
        "undefined": ["AF", "OF"],
        "defined": ["SF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "SHLD": {
        "undefined": ["AF", "OF"],
        "defined": ["SF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "SHR": {
        "undefined": ["OF", "AF"],
        "defined": ["SF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "SHRD": {
        "undefined": ["OF", "AF"],
        "defined": ["SF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "STC": {
        "undefined": [],
        "defined": ["CF"],
        "setted": ["CF"],
        "modified": ["CF"],
        "tested": [],
        "cleared": [],
    },
    "STD": {
        "undefined": [],
        "defined": ["DF"],
        "setted": ["DF"],
        "modified": ["DF"],
        "tested": [],
        "cleared": [],
    },
    "STI": {
        "undefined": [],
        "defined": ["IF"],
        "setted": ["IF"],
        "modified": ["IF"],
        "tested": [],
        "cleared": [],
    },
    "STOS": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "STOSB": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "STOSD": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "STOSQ": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "STOSW": {
        "undefined": [],
        "defined": [],
        "setted": [],
        "modified": [],
        "tested": ["DF"],
        "cleared": [],
    },
    "SUB": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "SYSENTER": {
        "undefined": [],
        "defined": ["IF"],
        "setted": [],
        "modified": ["IF"],
        "tested": [],
        "cleared": ["IF"],
    },
    "TEST": {
        "undefined": ["AF"],
        "defined": ["OF", "SF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": ["OF", "CF"],
    },
    "UCOMISD": {
        "undefined": [],
        "defined": ["ZF", "PF", "CF"],
        "setted": [],
        "modified": ["ZF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "UCOMISS": {
        "undefined": [],
        "defined": ["ZF", "PF", "CF"],
        "setted": [],
        "modified": ["ZF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "VERR": {
        "undefined": [],
        "defined": ["ZF"],
        "setted": [],
        "modified": ["ZF"],
        "tested": [],
        "cleared": [],
    },
    "VERW": {
        "undefined": [],
        "defined": ["ZF"],
        "setted": [],
        "modified": ["ZF"],
        "tested": [],
        "cleared": [],
    },
    "VMCALL": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "VMCLEAR": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "VMLAUNCH": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "VMPTRLD": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "VMPTRST": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "VMREAD": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "VMRESUME": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "VMWRITE": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "VMXOFF": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "VMXON": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "XADD": {
        "undefined": [],
        "defined": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": [],
    },
    "XOR": {
        "undefined": ["AF"],
        "defined": ["OF", "SF", "ZF", "PF", "CF"],
        "setted": [],
        "modified": ["OF", "SF", "ZF", "AF", "PF", "CF"],
        "tested": [],
        "cleared": ["OF", "CF"],
    },
}
