init:
  test -d venv || python3 -m venv venv
  . venv/bin/activate; pip install -U setuptools pip wheel; pip install -e .[dev]

format:
  ruff format .
  ruff check --fix .

lint:
  ruff format --check .
  ruff check .
  mypy

generate:
  python3 generate.py

build: generate
  #!/usr/bin/env bash
  set -euo
  mkdir -p dist
  py_ver=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
  python3 -m shiv -c manticore_server -o dist/manticore_server --reproducible --no-modify --python "/usr/bin/env python${py_ver}" --compressed .

test:
  python3 -m unittest tests/test_*.py
