# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from muicore import MUICore_pb2 as muicore_dot_MUICore__pb2


class ManticoreUIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartNative = channel.unary_unary(
                '/muicore.ManticoreUI/StartNative',
                request_serializer=muicore_dot_MUICore__pb2.NativeArguments.SerializeToString,
                response_deserializer=muicore_dot_MUICore__pb2.ManticoreInstance.FromString,
                )
        self.StartEVM = channel.unary_unary(
                '/muicore.ManticoreUI/StartEVM',
                request_serializer=muicore_dot_MUICore__pb2.EVMArguments.SerializeToString,
                response_deserializer=muicore_dot_MUICore__pb2.ManticoreInstance.FromString,
                )
        self.Terminate = channel.unary_unary(
                '/muicore.ManticoreUI/Terminate',
                request_serializer=muicore_dot_MUICore__pb2.ManticoreInstance.SerializeToString,
                response_deserializer=muicore_dot_MUICore__pb2.TerminateResponse.FromString,
                )
        self.GetStateList = channel.unary_unary(
                '/muicore.ManticoreUI/GetStateList',
                request_serializer=muicore_dot_MUICore__pb2.ManticoreInstance.SerializeToString,
                response_deserializer=muicore_dot_MUICore__pb2.MUIStateList.FromString,
                )
        self.GetMessageList = channel.unary_unary(
                '/muicore.ManticoreUI/GetMessageList',
                request_serializer=muicore_dot_MUICore__pb2.ManticoreInstance.SerializeToString,
                response_deserializer=muicore_dot_MUICore__pb2.MUIMessageList.FromString,
                )
        self.CheckManticoreRunning = channel.unary_unary(
                '/muicore.ManticoreUI/CheckManticoreRunning',
                request_serializer=muicore_dot_MUICore__pb2.ManticoreInstance.SerializeToString,
                response_deserializer=muicore_dot_MUICore__pb2.ManticoreRunningStatus.FromString,
                )
        self.StopServer = channel.unary_unary(
                '/muicore.ManticoreUI/StopServer',
                request_serializer=muicore_dot_MUICore__pb2.StopServerRequest.SerializeToString,
                response_deserializer=muicore_dot_MUICore__pb2.StopServerResponse.FromString,
                )
        self.ControlState = channel.unary_unary(
                '/muicore.ManticoreUI/ControlState',
                request_serializer=muicore_dot_MUICore__pb2.ControlStateRequest.SerializeToString,
                response_deserializer=muicore_dot_MUICore__pb2.ControlStateResponse.FromString,
                )


class ManticoreUIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartNative(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartEVM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckManticoreRunning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManticoreUIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartNative': grpc.unary_unary_rpc_method_handler(
                    servicer.StartNative,
                    request_deserializer=muicore_dot_MUICore__pb2.NativeArguments.FromString,
                    response_serializer=muicore_dot_MUICore__pb2.ManticoreInstance.SerializeToString,
            ),
            'StartEVM': grpc.unary_unary_rpc_method_handler(
                    servicer.StartEVM,
                    request_deserializer=muicore_dot_MUICore__pb2.EVMArguments.FromString,
                    response_serializer=muicore_dot_MUICore__pb2.ManticoreInstance.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=muicore_dot_MUICore__pb2.ManticoreInstance.FromString,
                    response_serializer=muicore_dot_MUICore__pb2.TerminateResponse.SerializeToString,
            ),
            'GetStateList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateList,
                    request_deserializer=muicore_dot_MUICore__pb2.ManticoreInstance.FromString,
                    response_serializer=muicore_dot_MUICore__pb2.MUIStateList.SerializeToString,
            ),
            'GetMessageList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageList,
                    request_deserializer=muicore_dot_MUICore__pb2.ManticoreInstance.FromString,
                    response_serializer=muicore_dot_MUICore__pb2.MUIMessageList.SerializeToString,
            ),
            'CheckManticoreRunning': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckManticoreRunning,
                    request_deserializer=muicore_dot_MUICore__pb2.ManticoreInstance.FromString,
                    response_serializer=muicore_dot_MUICore__pb2.ManticoreRunningStatus.SerializeToString,
            ),
            'StopServer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopServer,
                    request_deserializer=muicore_dot_MUICore__pb2.StopServerRequest.FromString,
                    response_serializer=muicore_dot_MUICore__pb2.StopServerResponse.SerializeToString,
            ),
            'ControlState': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlState,
                    request_deserializer=muicore_dot_MUICore__pb2.ControlStateRequest.FromString,
                    response_serializer=muicore_dot_MUICore__pb2.ControlStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'muicore.ManticoreUI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ManticoreUI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartNative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muicore.ManticoreUI/StartNative',
            muicore_dot_MUICore__pb2.NativeArguments.SerializeToString,
            muicore_dot_MUICore__pb2.ManticoreInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartEVM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muicore.ManticoreUI/StartEVM',
            muicore_dot_MUICore__pb2.EVMArguments.SerializeToString,
            muicore_dot_MUICore__pb2.ManticoreInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muicore.ManticoreUI/Terminate',
            muicore_dot_MUICore__pb2.ManticoreInstance.SerializeToString,
            muicore_dot_MUICore__pb2.TerminateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStateList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muicore.ManticoreUI/GetStateList',
            muicore_dot_MUICore__pb2.ManticoreInstance.SerializeToString,
            muicore_dot_MUICore__pb2.MUIStateList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessageList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muicore.ManticoreUI/GetMessageList',
            muicore_dot_MUICore__pb2.ManticoreInstance.SerializeToString,
            muicore_dot_MUICore__pb2.MUIMessageList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckManticoreRunning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muicore.ManticoreUI/CheckManticoreRunning',
            muicore_dot_MUICore__pb2.ManticoreInstance.SerializeToString,
            muicore_dot_MUICore__pb2.ManticoreRunningStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muicore.ManticoreUI/StopServer',
            muicore_dot_MUICore__pb2.StopServerRequest.SerializeToString,
            muicore_dot_MUICore__pb2.StopServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ControlState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/muicore.ManticoreUI/ControlState',
            muicore_dot_MUICore__pb2.ControlStateRequest.SerializeToString,
            muicore_dot_MUICore__pb2.ControlStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
