name: pip-audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: [ cron: "0 7 * * 2" ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Manticore
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install .
    - name: Run pip-audit
      uses: pypa/gh-action-pip-audit@v1.0.6
